"""draw Phase, Tempture"""
#the following files(draw_diagram,flac) must exist in the same level as the reading files

"""haven't finish, draw velocity vector"""

import os
import sys
import flac
import numpy as np
from pathlib import Path
from matplotlib.cm import get_cmap
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.colors import Normalize, BoundaryNorm, ListedColormap

    
"""read data"""  
def read_time():
    with open('_contents.0') as contents:
        time = contents.read() #time_step, loop, and time        
    return time
def read_flac(frame):
    phase = fl.read_phase(frame)
    return phase

def read_temperature(frame):
    temp = fl.read_temperature(frame)
    return temp
def read_srII(frame): #strain rate
    srII = fl.read_srII(frame)
    return srII
def read_aps(frame):
    aps = fl.read_aps(frame)
    return aps
def read_visc(frame):
    visc = fl.read_visc(frame)
    return visc
def read_sxx(frame):
    sxx = fl.read_sxx(frame)
    return sxx
def read_sII(frame):
    sII = fl.read_sII(frame)
    return sII
def read_vel(frame):
    vx, vz = fl.read_vel(frame)
    return vx, vz
"""set parameter"""  
def set_time(time):  
    row_str = time.strip().split('\n')
    time_list = []
    for row in row_str:
        element = row.split()
        time_list.append(element)
    time = np.array(time_list)
    time = time.astype(float)
    
    return time
def set_grid(frame):
    
    #set the grid size of the specific area of intrest 
    grid_size = int(0)
    
    x,z = fl.read_mesh(frame) #get the x and z coordinate
    sub_xz = [200.0,1000.0,-50.0,10.0] #(left,right,bottom,top) km
    
    if grid_size != 0:
        print("draw whole grid")
   
    return x,z,sub_xz,grid_size

def set_canvas():
    shrink_col = int(42) #whole grid = 30
    shrink_row = int(7) #whole grid = 10
    canvas_row = int(6)
    canvas_col = int(1)
    total_position = canvas_row * canvas_col
    canvas_row_init = int(0)
    canvas_col_init = int(0)
    canvas_grid_position = []
    
    for i in range(canvas_row_init, canvas_row):
        for j in range(canvas_col_init, canvas_col):
    
            grid_position = (i,j)
            canvas_grid_position.append(grid_position)
            
    GRID_DIMS = (canvas_row,canvas_col) #draw to graph only right know, 
    fig_large = plt.figure(figsize=(canvas_col * shrink_col , canvas_row * shrink_row ))  #figure_large is the large canvas that figure is putting on
    gs = GridSpec(*GRID_DIMS, figure = fig_large)
    font_size = int(40) #change fontsize, whole grid = 40
    label_size =int(40) #change labelsize, whole_grid = 20
    return gs, canvas_grid_position, total_position,fig_large, font_size, label_size

def set_color():
    phase = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]) 
    all_phase_color = [
        "lightblue",        #phase1: basalt(anhydrate)
        "darkgreen",        #phase2: continental  crust
        "blue",             #phase3: basalt(ocean crust)
        "white",            #phase4: olvine(mantle)
        "limegreen",        #phase5: schist, transformed from #17    
        "olivedrab",        #phase6: continental crust, same as #2
        "cyan",             #phase7: basalt (oceanic crust), same as #3
        "gray",             #phase8: olivine (mantle), same as #4.
        "darkred",          #phase9: serpentinite (weak mantle), transformed from mantle (#4, #8) if residing above subducted oceanic crust and sediment (#3, #7, #10). Will transform to hydrated mantle (#16) when T-P conditions are high enough.c
        "teal",             #phase10: sedimentary rock, compacted from (#11)
        "green",           #phase11: weak continental crust, transformed from continental crust (#2, #6) if residing above oceanic crust, sediment, or arc (#3, #7, #10, #14).
        "aqua",             #phase12: eclogite, transformed from basal (#1, #3, #7) when T-P conditions are high enough.
        "pink",             #phase13: arc crust, generated by arc volcanism
        "black",            #phase14: weak middle crust, transformed from continental crust (#3, #7) if stressed and heated. Disabled.
        "lightgray",        #phase15: hydrated mantle, will transform (partially melt) to mantle (#4) if warmer than olivine wet solidus and generate arc (#14) at surface.
        "darkslategrey",    #phase16: metamormpic sedimentary rock, transformed from (#10)
        "darkgray",         #phase17: dry mantle, stronger than (#4)
        "black",            #phase18: custom
        "black",            #phase19: custom
        ]
    phase_color = all_phase_color[:] #select phase color with in all_phase_color
        
    return phase_color

""" plot diagram """
def plot_phase(phase,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size):
    
    
    row,col = canvas_grid_position[canvas_position_counter]
    ax = fig_large.add_subplot(gs[row,col])
    phase_color = set_color() #custom the phase color
    phase_cmap = ListedColormap(phase_color)
    bounds = np.arange(1, 20)   
    norm = BoundaryNorm(bounds, phase_cmap.N)
    
    phase_mesh = ax.pcolormesh(x , z, phase,cmap=phase_cmap,norm = norm, shading='auto') #plot phase
    phase_mesh = add_temp(phase_mesh,temp,x,z,fig_large,ax,label_size) #add temp to figure
    
    ax.tick_params(axis='x',labelsize = font_size)
    ax.tick_params(axis='y',labelsize = font_size)
    if grid_size ==0:
        ax.set_xlim(sub_xz[0],sub_xz[1])
        ax.set_ylim(sub_xz[2],sub_xz[3])
    ax.set_aspect('equal')
    colorbar = fig_large.colorbar(phase_mesh,label='phase',orientation='horizontal',shrink = 15,aspect = 15)
    cbar_ax = colorbar.ax
    cbar_ax.set_xlabel('phase', fontsize=font_size)
    colorbar.ax.tick_params(axis='x',labelsize =label_size)
    
    canvas_position_counter = position_counter(canvas_position_counter,canvas_grid_position)
    
    return  canvas_position_counter
    
def plot_srII(srII,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size):
    
    row,col = canvas_grid_position[canvas_position_counter]
    
    max_srII = -(12.5)
    min_srII = -(15.0)
    
    ax = fig_large.add_subplot(gs[row,col])
    srII_mesh = ax.pcolormesh(x,z,srII,cmap = 'jet',vmax = max_srII,vmin = min_srII)
    
    srII_mesh = add_temp(srII_mesh,temp,x,z,fig_large,ax,label_size) #add temp to figure
    
    ax.tick_params(axis='x',labelsize = font_size)
    ax.tick_params(axis='y',labelsize = font_size)
    if grid_size ==0:
        ax.set_xlim(sub_xz[0],sub_xz[1])
        ax.set_ylim(sub_xz[2],sub_xz[3])
    ax.set_aspect('equal')
    colorbar = fig_large.colorbar(srII_mesh,label='strainrate',orientation='horizontal',shrink = 15,aspect = 15)
    cbar_ax = colorbar.ax
    cbar_ax.set_xlabel('strain rate', fontsize=font_size)
    colorbar.ax.tick_params(axis='x',labelsize =label_size)
    canvas_position_counter = position_counter(canvas_position_counter,canvas_grid_position)
    
    return canvas_position_counter

def plot_aps(aps,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size): 
    
    row,col = canvas_grid_position[canvas_position_counter]
    
    max_aps = 2.0
    min_aps = 0.0
    
    ax = fig_large.add_subplot(gs[row,col])
    aps_mesh = ax.pcolormesh(x,z,aps,cmap = 'Blues',vmax = max_aps, vmin = min_aps)
    aps_mesh = add_temp(aps_mesh,temp,x,z,fig_large,ax,label_size) #add temp to figure
    ax.tick_params(axis='x',labelsize = font_size)
    ax.tick_params(axis='y',labelsize = font_size)
    if grid_size ==0:
        ax.set_xlim(sub_xz[0],sub_xz[1])
        ax.set_ylim(sub_xz[2],sub_xz[3])
    ax.set_aspect('equal')
    colorbar = fig_large.colorbar(aps_mesh,label='plastic strain',orientation='horizontal',shrink = 15,aspect = 15)
    cbar_ax = colorbar.ax
    cbar_ax.set_xlabel('plastic strain', fontsize=font_size)
    colorbar.ax.tick_params(axis='x',labelsize =label_size)
    canvas_position_counter = position_counter(canvas_position_counter,canvas_grid_position)

    return canvas_position_counter

def plot_visc(visc,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size):
    
    row,col = canvas_grid_position[canvas_position_counter]
    
    max_visc = 25.0
    min_visc = 19.0
    ax = fig_large.add_subplot(gs[row,col])
    visc_mesh = ax.pcolormesh(x,z,visc,cmap = 'jet',vmax = max_visc, vmin = min_visc)
    visc_mesh = add_temp(visc_mesh,temp,x,z,fig_large,ax,label_size) #add temp to figure
    ax.tick_params(axis='x',labelsize = font_size)
    ax.tick_params(axis='y',labelsize = font_size)
    if grid_size ==0:
        ax.set_xlim(sub_xz[0],sub_xz[1])
        ax.set_ylim(sub_xz[2],sub_xz[3])
    ax.set_aspect('equal')
    colorbar = fig_large.colorbar(visc_mesh,label='viscosity',orientation='horizontal',shrink = 15,aspect = 15)
    cbar_ax = colorbar.ax
    cbar_ax.set_xlabel('viscosity', fontsize= font_size)
    colorbar.ax.tick_params(axis='x',labelsize =label_size)
    canvas_position_counter = position_counter(canvas_position_counter,canvas_grid_position)
    
    return canvas_position_counter

def plot_sxx(sxx,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size):
    
    row,col = canvas_grid_position[canvas_position_counter]
    
    max_sxx = 15.0
    min_sxx = -15.0
    ax = fig_large.add_subplot(gs[row,col])
    sxx_mesh = ax.pcolormesh(x,z,sxx,cmap = 'bwr',vmax = max_sxx, vmin = min_sxx)
    sxx_mesh = add_temp(sxx_mesh,temp,x,z,fig_large,ax,label_size) #add temp to figure
    ax.tick_params(axis='x',labelsize = font_size)
    ax.tick_params(axis='y',labelsize = font_size)
    if grid_size ==0:
        ax.set_xlim(sub_xz[0],sub_xz[1])
        ax.set_ylim(sub_xz[2],sub_xz[3])
    ax.set_aspect('equal')
    colorbar = fig_large.colorbar(sxx_mesh,label='sxx',orientation='horizontal',shrink = 15,aspect = 15)
    cbar_ax = colorbar.ax
    cbar_ax.set_xlabel('sxx', fontsize=font_size)
    colorbar.ax.tick_params(axis='x',labelsize =label_size)
    canvas_position_counter = position_counter(canvas_position_counter,canvas_grid_position)
    
    return canvas_position_counter
def plot_sII(sII,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size):
    
    row,col = canvas_grid_position[canvas_position_counter]
    
    max_sII = 10.0
    min_sII = 0.0
    ax = fig_large.add_subplot(gs[row,col])
    sII_mesh = ax.pcolormesh(x,z,sII,cmap = 'Greys',vmax = max_sII, vmin = min_sII)
    canvas_position_counter = position_counter(canvas_position_counter,canvas_grid_position)
    sII_mesh = add_temp(sII_mesh,temp,x,z,fig_large,ax,label_size) #add temp to figure
    ax.tick_params(axis='x',labelsize = font_size)
    ax.tick_params(axis='y',labelsize = font_size)
    if grid_size ==0:
        ax.set_xlim(sub_xz[0],sub_xz[1])
        ax.set_ylim(sub_xz[2],sub_xz[3])    
    ax.set_aspect('equal')
    colorbar = fig_large.colorbar(sII_mesh,label='stress',orientation='horizontal',shrink = 15,aspect = 15)
    cbar_ax = colorbar.ax
    cbar_ax.set_xlabel('stress', fontsize = font_size)
    colorbar.ax.tick_params(axis='x',labelsize =label_size)
    return canvas_position_counter

def add_temp(mesh,temp,x,z,fig_large,ax,label_size):
    
    temp_level = np.arange(0, 1400, 200)
    temp_cmap = plt.get_cmap('autumn')
    temp_contourf = ax.contour(x,z,temp,levels = temp_level,cmap = temp_cmap)
    cbar = fig_large.colorbar(temp_contourf, ax=ax,shrink=1,pad=0)
    cbar.ax.tick_params(labelsize = label_size)
    ax.clabel(temp_contourf)
    return mesh

"""check values"""    

def position_counter(canvas_position_counter,canvas_grid_position):
             
    canvas_position_counter = canvas_position_counter + 1
    
    return canvas_position_counter

def print_result_to_check():
    
    return
def count_frame():
    
    max_frame = int(100)
    init_frame = int(1)
    total_frame = int(0)
    for frame in range(init_frame, max_frame):
        if frame > max_frame:
            print(f"reach maximum frame allowed,maximum of {max_frame}")
            break
        try:
            fl.read_mesh(frame) 
            pass
        except Exception as e:
            print(f"total frame of {frame}")
            total_frame = frame
            break     
    return init_frame, total_frame

"""main"""    
def main(): 
    

    init_frame, total_frame = count_frame()
    gs,canvas_grid_position,total_position,fig_large,font_size, label_size = set_canvas()
    time = read_time()
    time = set_time(time)
    
    for frame in range(init_frame,total_frame):
        
        canvas_position_counter = 0
        t = time[frame-1,2] #get the corresponding time of the time_step
        
        #read data
        phase = read_flac(frame)
        temp = read_temperature(frame)
        srII = read_srII(frame)
        aps = read_aps(frame)
        visc = read_visc(frame)
        sxx = read_sxx(frame)
        sII = read_sII(frame)
        vx,vz = read_vel(frame) 
        
        #set parameter
        x,z,sub_xz,grid_size = set_grid(frame)
        
        #plot diagram    
        canvas_position_counter = plot_phase(phase,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size)
        canvas_position_counter = plot_srII(srII,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size)
        canvas_position_counter = plot_aps(aps,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size)
        canvas_position_counter = plot_visc(visc,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size)
        canvas_position_counter = plot_sxx(sxx,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size)
        canvas_position_counter = plot_sII(sII,x,z,gs,canvas_grid_position,canvas_position_counter,fig_large,temp,font_size,label_size,sub_xz,grid_size)

        plt.tight_layout(rect = [0,0,1,0.95])
        fig_large.suptitle(f"time_step_{frame} at {t}Myr",fontsize=50)
        plt.savefig(f'time_step_{frame}',bbox_inches='tight')
        fig_large.clf() #clear legend to avoid stacking
        
        print(f"saved time_step_{frame}")
    print(f"finish saving time step, total of {total_frame} frame")
if __name__ == '__main__':
    
    fl = flac.Flac()
    main()
